Reactive methods: abort with `[Method]Aborted` like non-reactive (#5049)
* Propagate `Aborted` errors through reactive API

Before this commit, a Reboot method that aborted
in a reactive context would result in an exception
that looked like this:
```
Traceback (most recent call last):
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/execroot/com_github_reboot_dev_mono/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/execroot/com_github_reboot_dev_mono/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/execroot/com_github_reboot_dev_mono/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/execroot/com_github_reboot_dev_mono/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/sandbox/processwrapper-sandbox/184/execroot/com_github_reboot_dev_mono/bazel-out/k8-fastbuild/bin/tests/reboot/std/collections/sorted_map_tests_py.runfiles/com_github_reboot_dev_mono/tests/reboot/std/collections/sorted_map_tests.py", line 270, in test_limit_zero
    async for range_response in sorted_map.reactively().range(
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/sandbox/processwrapper-sandbox/184/execroot/com_github_reboot_dev_mono/bazel-out/k8-fastbuild/bin/tests/reboot/std/collections/sorted_map_tests_py.runfiles/com_github_reboot_dev_mono/rbt/std/collections/v1/sorted_map_rbt.py", line 7193, in Range
    async for __query_response__ in __call__:
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/sandbox/processwrapper-sandbox/184/execroot/com_github_reboot_dev_mono/bazel-out/k8-fastbuild/bin/tests/reboot/std/collections/sorted_map_tests_py.runfiles/rbt_pypi_grpcio/site-packages/grpc/aio/_call.py", line 356, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/sandbox/processwrapper-sandbox/184/execroot/com_github_reboot_dev_mono/bazel-out/k8-fastbuild/bin/tests/reboot/std/collections/sorted_map_tests_py.runfiles/rbt_pypi_grpcio/site-packages/grpc/aio/_call.py", line 263, in _raise_for_status
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.ABORTED
        details = ""
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-11-12T11:28:54.020052391+00:00", grpc_status:10, grpc_message:""}"
>
```

Needless to say this generic `AioRpcError` is missing crucial
information, like "what aborted" and "why did it
abort" - information that is present in the
original `[Method]Aborted` error.

This commit rehydrates the original `Aborted`
error also in reactive contexts, so that the error
now looks like:

```
Traceback (most recent call last):
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/execroot/com_github_reboot_dev_mono/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/execroot/com_github_reboot_dev_mono/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/execroot/com_github_reboot_dev_mono/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/execroot/com_github_reboot_dev_mono/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/sandbox/processwrapper-sandbox/192/execroot/com_github_reboot_dev_mono/bazel-out/k8-fastbuild/bin/tests/reboot/std/collections/sorted_map_tests_py.runfiles/com_github_reboot_dev_mono/tests/reboot/std/collections/sorted_map_tests.py", line 270, in test_limit_zero
    async for range_response in sorted_map.reactively().range(
  File "/home/vscode/.cache/bazel/_bazel_vscode/13febbc7ed60eff13c437d36e7c3ea8c/sandbox/processwrapper-sandbox/192/execroot/com_github_reboot_dev_mono/bazel-out/k8-fastbuild/bin/tests/reboot/std/collections/sorted_map_tests_py.runfiles/com_github_reboot_dev_mono/rbt/std/collections/v1/sorted_map_rbt.py", line 7242, in Range
    raise SortedMap.RangeAborted.from_status(
rbt.std.collections.v1.sorted_map_rbt.SortedMap.RangeAborted: aborted with 'InvalidRangeError { message: "Range requires a non-zero `limit` value." }'
```

* Update code template to work in more scenarios

A build failure in
`//tests/reboot/protoc:all_services_in_different_package_js_reboot_ts_reboot_files`
pointed out that we should spell the generated
code slightly differently to work with all
possible template inputs.

While here, also improve the error message when we
fail to render a template, to include the template
filename.

* Update goldens

* Fix `logs_servicer.py`