Improve `rbt cloud up` and `rbt cloud logs` UX (#4502)
* Deprecate obsolete `RegisterConsensus` RPC+state

The `ApplicationLogs.RegisterConsensus` RPC was
being called, but the state it produced
(`consensus_ids`) was never getting used. There is
no reason to have it.

This commit deprecates the RPC (we can't remove it
because of backwards compatibility checks) and
removes calls to it. It also removes the unused
state field it used to fill in.

* Log records can have non-consensus "source"

Before this commit, `LogRecord`s would be required
to have a `consensus_id`. If the source of the log
was a config pod, the `consensus_id` would be set
to "config" - which was a bit of a hack.

As we're making UX improvements to the logging
experience, it becomes important to distinguish
between logs from config pods vs consensuses more
clearly; the CLI will soon have the ability to
filter based on this. This commit makes "config
runs" (the non-Kubernetes-specific name for the
execution of a config pod) a different "source" in
the `LogRecord` message.

* Improve human-readability of config pod names

* Add revision number to 'LogRecord'

* `rbt cloud logs` UX improvements

This implements most of the improvements proposed
in #4314.

1. If the logs have multiple revisions or sources,
   print the revision number and source name in
   the log line. E.g.:
```
$ rbt cloud logs --source=all
[config=89c3cc02c1, revision=0] Using .rbtrc (from .rbtrc) and working directory .
[consensus=c000000, revision=0] Using .rbtrc (from .rbtrc) and working directory .
[consensus=c000000, revision=0] Yes! Message! Woohoo!
[consensus=c000000, revision=0] INFO:root:👋 Hello, World? Hello, Reboot! 👋
[config=ab995929f9, revision=1] Using .rbtrc (from .rbtrc) and working directory .
[consensus=c000000, revision=1] Using .rbtrc (from .rbtrc) and working directory .
[consensus=c000000, revision=1] INFO:root:👋 Hello, World? Hello, Reboot! 👋
[config=d671eb287b, revision=2] Using .rbtrc (from .rbtrc) and working directory .
[config=d671eb287b, revision=2] Traceback (most recent call last):
[config=d671eb287b, revision=2]   File "/app/backend/src/main.py", line 4, in <module>
[config=d671eb287b, revision=2]     from hello_servicer import HelloServicer
[config=d671eb287b, revision=2]   File "/app/backend/src/hello_servicer.py", line 1, in <module>
[config=d671eb287b, revision=2]     import Nope
[config=d671eb287b, revision=2] ModuleNotFoundError: No module named 'Nope'
[config=edc379bea0, revision=3] Using .rbtrc (from .rbtrc) and working directory .
[consensus=c000000, revision=3] Using .rbtrc (from .rbtrc) and working directory .
[consensus=c000000, revision=3] INFO:root:👋 Hello, World? Hello, Reboot! 👋
```
1. By passing `--revision=<revision_number>`, customers can filter
   their logs down to a single revision.
1. By passing `--source=consensus|config|all`, customers can filter
   their logs down to a single source type (config
   pod runs, or serving consensuses), or ask for
   all source types. By default shows only serving
   consensus logs (since the config runs are an
   implementation detail unless they are failing).
1. By passing `--show-revision` or
   `--show-source`, customers can show (or hide)
   the revision number or source name in the log
   line even if there is only one (or more)
   revision or source type.
1. By passing `--timestamp` customers can show
   the timestamp of the log line. Example:
```
$ rbt cloud logs --revision=3 --show-timestamp
[2025-05-08 13:04:38.933225+00:00] Using .rbtrc (from .rbtrc) and working directory .
[2025-05-08 13:04:40.108646+00:00] INFO:root:👋 Hello, World? Hello, Reboot! 👋
```

* Print a warning in case the user does not see any log lines, but there are log lines from other sources

* `rbt cloud up`: print config pod logs on failure

Before this commit, customers who ran `rbt cloud
up` and ended up with a crashing config pod and
therefore a failed deploy would see an error
message saying "something failed, check the logs"
- but no logs were printed.

This commit will print the logs of the config pod
that crashed, giving developers the debug
information they need to fix the issue.

Example (note that there's some helpful colors in
the terminal that don't translate to a git commit
message):

```
$ rbt cloud up
[😇] checking permissions... ✅
[🐳] building container from './Dockerfile'... ✅
[🚛] pushing container... ✅
[🚀] deploying... 🛑 failed:
  Could not deploy revision 4:
    Container failed before producing configuration - check application logs for more information

  ### Logs for revision 4 ###
  Using .rbtrc (from .rbtrc) and working directory .
  Traceback (most recent call last):
    File "/app/backend/src/main.py", line 4, in <module>
      from hello_servicer import HelloServicer
    File "/app/backend/src/hello_servicer.py", line 1, in <module>
      import ThisIsMyMistake
  ModuleNotFoundError: No module named 'ThisIsMyMistake'
  Using .rbtrc (from .rbtrc) and working directory .
  Traceback (most recent call last):
    File "/app/backend/src/main.py", line 4, in <module>
      from hello_servicer import HelloServicer
    File "/app/backend/src/hello_servicer.py", line 1, in <module>
      import ThisIsMyMistake
  ModuleNotFoundError: No module named 'ThisIsMyMistake'
  ### End of logs for revision 4 ###
  Please correct the issue and try again.
```

* Reject 'Logs' requests for applications that are down (== expunged)

* Fix runtime type error message in generated code

This isn't related to the rest of the PR, but it
was found during development so why not fix it
straight away.

* Address review comment