Rename `reboot.logging` to `reboot.log`
This avoids an erroneous circular import from the
Python standard library:
```
  Traceback (most recent call last):
    File "/home/vscode/.cache/bazel/_bazel_vscode/e9b5149ef40c40531841044f5a70254d/sandbox/processwrapper-sandbox/8304/execroot/com_github_reboot_dev_respect/bazel-out/k8-fastbuild-exec-2B5CBBC6/bin/reboot/protoc-gen-reboot_python.runfiles/com_github_reboot_dev_respect/reboot/protoc_gen_reboot_python.py", line 13, in <module>
      from reboot.cli import terminal
    File "/home/vscode/.cache/bazel/_bazel_vscode/e9b5149ef40c40531841044f5a70254d/sandbox/processwrapper-sandbox/8304/execroot/com_github_reboot_dev_respect/bazel-out/k8-fastbuild-exec-2B5CBBC6/bin/reboot/protoc-gen-reboot_python.runfiles/com_github_reboot_dev_respect/reboot/cli/terminal.py", line 6, in <module>
      from reboot.aio.once import Once
    File "/home/vscode/.cache/bazel/_bazel_vscode/e9b5149ef40c40531841044f5a70254d/sandbox/processwrapper-sandbox/8304/execroot/com_github_reboot_dev_respect/bazel-out/k8-fastbuild-exec-2B5CBBC6/bin/reboot/protoc-gen-reboot_python.runfiles/com_github_reboot_dev_respect/reboot/aio/once.py", line 1, in <module>
      import asyncio
    File "/home/vscode/.cache/bazel/_bazel_vscode/e9b5149ef40c40531841044f5a70254d/execroot/com_github_reboot_dev_respect/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/asyncio/__init__.py", line 8, in <module>
      from .base_events import *
    File "/home/vscode/.cache/bazel/_bazel_vscode/e9b5149ef40c40531841044f5a70254d/execroot/com_github_reboot_dev_respect/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/asyncio/base_events.py", line 18, in <module>
      import concurrent.futures
    File "/home/vscode/.cache/bazel/_bazel_vscode/e9b5149ef40c40531841044f5a70254d/execroot/com_github_reboot_dev_respect/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/concurrent/futures/__init__.py", line 8, in <module>
      from concurrent.futures._base import (FIRST_COMPLETED,
    File "/home/vscode/.cache/bazel/_bazel_vscode/e9b5149ef40c40531841044f5a70254d/execroot/com_github_reboot_dev_respect/external/python3_10_12_x86_64-unknown-linux-gnu/lib/python3.10/concurrent/futures/_base.py", line 7, in <module>
      import logging
    File "/workspaces/respect/reboot/logging.py", line 6, in <module>
      from logging import CRITICAL, DEBUG, ERROR, INFO, WARNING  # noqa: F401
  ImportError: cannot import name 'CRITICAL' from partially initialized module 'logging' (most likely due to a circular import) (/workspaces/respect/reboot/logging.py)
```

Note that this `import logging` is misinterpreted
as `import reboot.logging`, probably due to the
`from .base_events import *` earlier in the chain
using a relative import.

Renaming `logging` to `log` avoids the naming
collision and thereby the circular import.